### ISSUE TITLE
Crystal code output should include blank lines for readability

### ISSUE THREAD

**Issue by HCLarsen** [tamdaz/crygen#82]
Crystal best practices include blank lines between parts of a class to improve readability, such as between methods, or between properties and methods. When I make a basic class with one getter and one method, this is my output. There should be a blank line there between the getter and the method.

```cr
class FooParser < SuperClassParser
  getter value : JSON::Any
  def method(arg1 : String) : JSON::Any
    @value = JSON.parse(string)
  end
end
```

**Comment by tamdaz** [comment]
The issue has been solved. Feel free to let me know if you encounter any other problems. 👍

**Comment by HCLarsen** [comment]
Unfortunately it appears that this hasn't been fixed. I've updated my shards to the lastest version, and it's still the same.

This code:

```
    class_type = Crygen::Types::Class.new("FooParser", "SuperClassParser")
    class_type.add_property(CGE::PropVisibility::Getter, "value", "JSON::Any")

    new_method = CGT::Method.new("method", "JSON::Any")
    new_method.add_arg("arg1", "String")
    new_method.add_body("@value = JSON.parse(string)")
    class_type.add_method(new_method)

   class_type.generate
```

Is giving me this output:

```
    class FooParser < SuperClassParser
      getter value : JSON::Any
      def method(arg1 : String) : JSON::Any
        @value = JSON.parse(string)
      end
    end
```

**Comment by tamdaz** [comment]
Good catch, I'll fix that spacing issue between properties and methods.

**Comment by tamdaz** [comment]
@HCLarsen I wonder if you can try to install it with the latest commit to your shard.yml

```yml
dependencies:
  crygen:
    github: tamdaz/crygen
    commit: d4cca0e27cbf8cd16f3925dc1154496b7e3a5968
```

EDIT: The latest commit matches to the PR I've created.

**Comment by tamdaz** [comment]
Thank you for the tips, I (re)fixed the spacing issue between the mixins _(even properties, ivars and cvars)_ and the nested  classes and structs 😉. The code examples you gave me are added into the unit tests.

```yml
dependencies:
  crygen:
    github: tamdaz/crygen
    commit: 9b56159281d352645f1c1dfdb257f35e0e116b67
```

**Comment by tamdaz** [comment]
Maybe it might be interesting to add a class in a struct (or struct in a class). As all `Crygen::Types` classes implement `Crygen::Interfaces::GeneratorInterface`, we can add anything we want, whatever the classes. This is the strength of the interface.

**Comment by HCLarsen** [comment]
Runs perfectly with all my tests.

**Comment by tamdaz** [comment]
That's perfect! I'll close this issue as solved. 😉
